/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "sdwtpzwukcqvdyegisha"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkd3Rwend1a2NxdmR5ZWdpc2hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3MDU1NDUsImV4cCI6MjA4MDI4MTU0NX0.-nn19iOp6577nKJgmypqk-8fp1x_uJxyjV55LcuBzIM"
